### ISSUE TITLE
空指针异常,[swagger.globalOperationParameters]必须要配置?

### ISSUE THREAD

**Issue by michael-ancestor** [dyc87112/spring-boot-starter-swagger#20]
文档里没看到必须要配置[swagger.globalOperationParameters]，现在如果不配置它的话，就会报空指针异常,部分信息如下:

``` java
Caused by: java.lang.NullPointerException
        at com.didispace.swagger.SwaggerAutoConfiguration.buildGlobalOperationParametersFromSwaggerProperties(SwaggerAutoConfiguration.java:174)
        at com.didispace.swagger.SwaggerAutoConfiguration.createRestApi(SwaggerAutoConfiguration.java:91)
        at com.didispace.swagger.SwaggerAutoConfiguration$$EnhancerBySpringCGLIB$$9bbeafcd.CGLIB$createRestApi$2(<generated>)
        at com.didispace.swagger.SwaggerAutoConfiguration$$EnhancerBySpringCGLIB$$9bbeafcd$$FastClassBySpringCGLIB$$aaa6c4eb.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
        at com.didispace.swagger.SwaggerAutoConfiguration$$EnhancerBySpringCGLIB$$9bbeafcd.createRestApi(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by dyc87112** [comment]
@renlulu 看着像bug，优化一下？

**Comment by renlulu** [comment]
感谢！在1.4.1修复了，横竖测试了一下。恳请各位大佬帮我验证...

**Comment by dyc87112** [comment]
1.4.1已修复
